script: rake ci
language: ruby
rvm:
  - 1.9.3
  - 2.2.0
  - jruby
  - rbx-2
  - ruby-head
  - jruby-head

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
    - env: CLLLD_BYPASS_FLAKY=true CLLLD_TASK_CLASS=Celluloid::TaskFiber
    - env: CLLLD_BYPASS_FLAKY=true CLLLD_TASK_CLASS=Celluloid::TaskThread
env:
  - CLLLD_BYPASS_FLAKY=true CLLLD_TASK_CLASS=Celluloid::TaskFiber
  - CLLLD_BYPASS_FLAKY=false CLLLD_TASK_CLASS=Celluloid::TaskFiber
  - CLLLD_BYPASS_FLAKY=true CLLLD_TASK_CLASS=Celluloid::TaskThread
  - CLLLD_BYPASS_FLAKY=false CLLLD_TASK_CLASS=Celluloid::TaskThread

notifications:
  irc: "irc.freenode.org#celluloid"

before_install:
  # Only use 1 job until Travis fixes the rbx --jobs issue.
  - if [ "$TRAVIS_RUBY_VERSION" == "rbx-2" ] ; then export BUNDLE_JOBS=1 ; else export BUNDLE_JOBS=4; fi

sudo: false
install: bundle install --retry=3 --without=development
